INSERT INTO ob_entreprise VALUES (ob_entreprise_ty('1','Walusa sarl','Bruebach','Alsace'));
INSERT INTO ob_entreprise VALUES (ob_entreprise_ty('2','Thales','Velizy','Essonne'));
INSERT INTO ob_entreprise VALUES (ob_entreprise_ty('3','MURRTECHNIC','Richwiller','Alsace'));
INSERT INTO ob_entreprise VALUES (ob_entreprise_ty('4','Charlatte réservoirs','Migennes','Bourgogne'));
INSERT INTO ob_entreprise VALUES (ob_entreprise_ty('5','Louis sarl','Paris','Paris'));
INSERT INTO ob_entreprise VALUES (ob_entreprise_ty('6','Bernard bruche france','Fontainebleau','Essonne'));
INSERT INTO ob_entreprise VALUES (ob_entreprise_ty('7','Lelievre','Croissy beaubourg','Seine-et-Marne'));
INSERT INTO ob_entreprise VALUES (ob_entreprise_ty('8','Biddle','Croissy beaubourg','Seine-et-Marne'));
INSERT INTO ob_entreprise VALUES (ob_entreprise_ty('9','Senitox','Valenton','Val-de-Marne'));
INSERT INTO ob_entreprise VALUES (ob_entreprise_ty('10','Hitec','Champlan','Essonne'));
INSERT INTO ob_entreprise VALUES (ob_entreprise_ty('11','Sanapra','Saint Maur des fosses','Val-de-Marne'));
INSERT INTO ob_entreprise VALUES (ob_entreprise_ty('12','Ravas sarl','Paris','Paris'));
INSERT INTO ob_entreprise VALUES (ob_entreprise_ty('13','Wam france','Tremblay en france','Seine-Saint-Denis'));
INSERT INTO ob_entreprise VALUES (ob_entreprise_ty('14','Facility','Chanteloup les vignes','Yvelines'));
INSERT INTO ob_entreprise VALUES (ob_entreprise_ty('15','Villadelles','Levallois Perret','Hauts-de-Seine'));

INSERT INTO ob_stage SELECT 1,Ref(ent),TO_DATE('01/02/2010','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =1;
INSERT INTO ob_stage SELECT 2,Ref(ent),TO_DATE('02/02/2010','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =8;
INSERT INTO ob_stage SELECT 3,Ref(ent),TO_DATE('03/02/2010','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =4;
INSERT INTO ob_stage SELECT 4,Ref(ent),TO_DATE('04/02/2010','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =3;
INSERT INTO ob_stage SELECT 5,Ref(ent),TO_DATE('05/02/2010','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =13;
INSERT INTO ob_stage SELECT 6,Ref(ent),TO_DATE('06/02/2010','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =6;
INSERT INTO ob_stage SELECT 7,Ref(ent),TO_DATE('07/02/2010','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =7;
INSERT INTO ob_stage SELECT 8,Ref(ent),TO_DATE('08/02/2011','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =7;
INSERT INTO ob_stage SELECT 9,Ref(ent),TO_DATE('09/02/2011','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =12;
INSERT INTO ob_stage SELECT 10,Ref(ent),TO_DATE('10/02/2011','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =3;
INSERT INTO ob_stage SELECT 11,Ref(ent),TO_DATE('11/02/2011','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =11;
INSERT INTO ob_stage SELECT 12,Ref(ent),TO_DATE('12/02/2011','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =10;
INSERT INTO ob_stage SELECT 13,Ref(ent),TO_DATE('13/02/2011','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =6;
INSERT INTO ob_stage SELECT 14,Ref(ent),TO_DATE('14/02/2011','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =2;
INSERT INTO ob_stage SELECT 15,Ref(ent),TO_DATE('15/02/2012','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =4;
INSERT INTO ob_stage SELECT 16,Ref(ent),TO_DATE('16/02/2012','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =12;
INSERT INTO ob_stage SELECT 17,Ref(ent),TO_DATE('17/02/2012','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =5;
INSERT INTO ob_stage SELECT 18,Ref(ent),TO_DATE('18/02/2012','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =5;
INSERT INTO ob_stage SELECT 19,Ref(ent),TO_DATE('19/02/2012','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =1;
INSERT INTO ob_stage SELECT 20,Ref(ent),TO_DATE('20/02/2012','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =2;
INSERT INTO ob_stage SELECT 21,Ref(ent),TO_DATE('21/02/2012','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =14;
INSERT INTO ob_stage SELECT 22,Ref(ent),TO_DATE('22/02/2013','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =8;
INSERT INTO ob_stage SELECT 23,Ref(ent),TO_DATE('23/02/2013','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =14;
INSERT INTO ob_stage SELECT 24,Ref(ent),TO_DATE('24/02/2013','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =4;
INSERT INTO ob_stage SELECT 25,Ref(ent),TO_DATE('25/02/2013','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =7;
INSERT INTO ob_stage SELECT 26,Ref(ent),TO_DATE('26/02/2013','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =9;
INSERT INTO ob_stage SELECT 27,Ref(ent),TO_DATE('27/02/2013','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =14;
INSERT INTO ob_stage SELECT 28,Ref(ent),TO_DATE('28/02/2013','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =7;
INSERT INTO ob_stage SELECT 29,Ref(ent),TO_DATE('01/03/2014','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =12;
INSERT INTO ob_stage SELECT 30,Ref(ent),TO_DATE('02/03/2014','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =12;
INSERT INTO ob_stage SELECT 31,Ref(ent),TO_DATE('03/03/2014','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =10;
INSERT INTO ob_stage SELECT 32,Ref(ent),TO_DATE('04/03/2014','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =7;
INSERT INTO ob_stage SELECT 33,Ref(ent),TO_DATE('05/03/2014','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =10;
INSERT INTO ob_stage SELECT 34,Ref(ent),TO_DATE('06/03/2014','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =6;
INSERT INTO ob_stage SELECT 35,Ref(ent),TO_DATE('07/03/2014','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =13;
INSERT INTO ob_stage SELECT 36,Ref(ent),TO_DATE('08/03/2015','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =6;
INSERT INTO ob_stage SELECT 37,Ref(ent),TO_DATE('09/03/2015','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =12;
INSERT INTO ob_stage SELECT 38,Ref(ent),TO_DATE('10/03/2015','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =6;
INSERT INTO ob_stage SELECT 39,Ref(ent),TO_DATE('11/03/2015','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =13;
INSERT INTO ob_stage SELECT 40,Ref(ent),TO_DATE('12/03/2015','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =4;
INSERT INTO ob_stage SELECT 41,Ref(ent),TO_DATE('13/03/2015','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =3;
INSERT INTO ob_stage SELECT 42,Ref(ent),TO_DATE('14/03/2015','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =1;
INSERT INTO ob_stage SELECT 43,Ref(ent),TO_DATE('15/03/2016','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =10;
INSERT INTO ob_stage SELECT 44,Ref(ent),TO_DATE('16/03/2016','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =8;
INSERT INTO ob_stage SELECT 45,Ref(ent),TO_DATE('17/03/2016','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =11;
INSERT INTO ob_stage SELECT 46,Ref(ent),TO_DATE('18/03/2016','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =4;
INSERT INTO ob_stage SELECT 47,Ref(ent),TO_DATE('19/03/2016','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =4;
INSERT INTO ob_stage SELECT 48,Ref(ent),TO_DATE('20/03/2016','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =5;
INSERT INTO ob_stage SELECT 49,Ref(ent),TO_DATE('21/03/2016','DD/MM/YYYY')FROM ob_entreprise ent WHERE numEntreprise =10;

INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('9','nom9','prenom9',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('10','nom10','prenom10',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('11','nom11','prenom11',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('12','nom12','prenom12',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('13','nom13','prenom13',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('14','nom14','prenom14',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('15','nom15','prenom15',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('16','nom16','prenom16',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('17','nom17','prenom17',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('18','nom18','prenom18',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('19','nom19','prenom19',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('20','nom20','prenom20',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('21','nom21','prenom21',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('22','nom22','prenom22',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('23','nom23','prenom23',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('24','nom24','prenom24',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('25','nom25','prenom25',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('26','nom26','prenom26',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('27','nom27','prenom27',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('28','nom28','prenom28',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('29','nom29','prenom29',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('30','nom30','prenom30',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('31','nom31','prenom31',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('32','nom32','prenom32',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('33','nom33','prenom33',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('34','nom34','prenom34',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('35','nom35','prenom35',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('36','nom36','prenom36',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('37','nom37','prenom37',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('38','nom38','prenom38',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('39','nom39','prenom39',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('40','nom40','prenom40',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('41','nom41','prenom41',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('42','nom42','prenom42',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('43','nom43','prenom43',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('44','nom44','prenom44',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('45','nom45','prenom45',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('46','nom46','prenom46',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('47','nom47','prenom47',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('48','nom48','prenom48',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('49','nom49','prenom49',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('50','nom50','prenom50',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('51','nom51','prenom51',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('52','nom52','prenom52',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('53','nom53','prenom53',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('54','nom54','prenom54',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('55','nom55','prenom55',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('56','nom56','prenom56',null));
INSERT INTO ob_etudiant VALUES(ob_etudiant_ty('57','nom57','prenom57',null));

INSERT INTO ob_etudiant SELECT 58,'nom68','prenom68',Ref(stage) FROM ob_stage stage WHERE numStage=48;
INSERT INTO ob_etudiant SELECT 59,'nom69','prenom69',Ref(stage) FROM ob_stage stage WHERE numStage=10;
INSERT INTO ob_etudiant SELECT 60,'nom70','prenom70',Ref(stage) FROM ob_stage stage WHERE numStage=25;
INSERT INTO ob_etudiant SELECT 61,'nom71','prenom71',Ref(stage) FROM ob_stage stage WHERE numStage=15;
INSERT INTO ob_etudiant SELECT 62,'nom72','prenom72',Ref(stage) FROM ob_stage stage WHERE numStage=47;
INSERT INTO ob_etudiant SELECT 63,'nom73','prenom73',Ref(stage) FROM ob_stage stage WHERE numStage=11;
INSERT INTO ob_etudiant SELECT 64,'nom74','prenom74',Ref(stage) FROM ob_stage stage WHERE numStage=42;
INSERT INTO ob_etudiant SELECT 65,'nom75','prenom75',Ref(stage) FROM ob_stage stage WHERE numStage=41;
INSERT INTO ob_etudiant SELECT 66,'nom76','prenom76',Ref(stage) FROM ob_stage stage WHERE numStage=31;
INSERT INTO ob_etudiant SELECT 67,'nom77','prenom77',Ref(stage) FROM ob_stage stage WHERE numStage=47;
INSERT INTO ob_etudiant SELECT 68,'nom78','prenom78',Ref(stage) FROM ob_stage stage WHERE numStage=47;
INSERT INTO ob_etudiant SELECT 69,'nom79','prenom79',Ref(stage) FROM ob_stage stage WHERE numStage=37;
INSERT INTO ob_etudiant SELECT 70,'nom80','prenom80',Ref(stage) FROM ob_stage stage WHERE numStage=20;
INSERT INTO ob_etudiant SELECT 71,'nom81','prenom81',Ref(stage) FROM ob_stage stage WHERE numStage=37;
INSERT INTO ob_etudiant SELECT 72,'nom82','prenom82',Ref(stage) FROM ob_stage stage WHERE numStage=26;
INSERT INTO ob_etudiant SELECT 73,'nom83','prenom83',Ref(stage) FROM ob_stage stage WHERE numStage=23;
INSERT INTO ob_etudiant SELECT 74,'nom84','prenom84',Ref(stage) FROM ob_stage stage WHERE numStage=21;
INSERT INTO ob_etudiant SELECT 75,'nom85','prenom85',Ref(stage) FROM ob_stage stage WHERE numStage=23;
INSERT INTO ob_etudiant SELECT 76,'nom86','prenom86',Ref(stage) FROM ob_stage stage WHERE numStage=43;
INSERT INTO ob_etudiant SELECT 77,'nom87','prenom87',Ref(stage) FROM ob_stage stage WHERE numStage=32;
INSERT INTO ob_etudiant SELECT 78,'nom88','prenom88',Ref(stage) FROM ob_stage stage WHERE numStage=33;
INSERT INTO ob_etudiant SELECT 79,'nom89','prenom89',Ref(stage) FROM ob_stage stage WHERE numStage=18;
INSERT INTO ob_etudiant SELECT 80,'nom90','prenom90',Ref(stage) FROM ob_stage stage WHERE numStage=38;
INSERT INTO ob_etudiant SELECT 81,'nom91','prenom91',Ref(stage) FROM ob_stage stage WHERE numStage=15;
INSERT INTO ob_etudiant SELECT 82,'nom92','prenom92',Ref(stage) FROM ob_stage stage WHERE numStage=16;
INSERT INTO ob_etudiant SELECT 83,'nom93','prenom93',Ref(stage) FROM ob_stage stage WHERE numStage=4;
INSERT INTO ob_etudiant SELECT 84,'nom94','prenom94',Ref(stage) FROM ob_stage stage WHERE numStage=17;
INSERT INTO ob_etudiant SELECT 85,'nom95','prenom95',Ref(stage) FROM ob_stage stage WHERE numStage=41;
INSERT INTO ob_etudiant SELECT 86,'nom96','prenom96',Ref(stage) FROM ob_stage stage WHERE numStage=41;
INSERT INTO ob_etudiant SELECT 87,'nom97','prenom97',Ref(stage) FROM ob_stage stage WHERE numStage=1;
INSERT INTO ob_etudiant SELECT 88,'nom98','prenom98',Ref(stage) FROM ob_stage stage WHERE numStage=11;
INSERT INTO ob_etudiant SELECT 89,'nom99','prenom99',Ref(stage) FROM ob_stage stage WHERE numStage=4;
INSERT INTO ob_etudiant SELECT 90,'nom100','prenom100',Ref(stage) FROM ob_stage stage WHERE numStage=23;
INSERT INTO ob_etudiant SELECT 91,'nom101','prenom101',Ref(stage) FROM ob_stage stage WHERE numStage=37;
INSERT INTO ob_etudiant SELECT 92,'nom102','prenom102',Ref(stage) FROM ob_stage stage WHERE numStage=31;
INSERT INTO ob_etudiant SELECT 93,'nom103','prenom103',Ref(stage) FROM ob_stage stage WHERE numStage=12;
INSERT INTO ob_etudiant SELECT 94,'nom104','prenom104',Ref(stage) FROM ob_stage stage WHERE numStage=19;
INSERT INTO ob_etudiant SELECT 95,'nom105','prenom105',Ref(stage) FROM ob_stage stage WHERE numStage=26;
INSERT INTO ob_etudiant SELECT 96,'nom106','prenom106',Ref(stage) FROM ob_stage stage WHERE numStage=13;
INSERT INTO ob_etudiant SELECT 97,'nom107','prenom107',Ref(stage) FROM ob_stage stage WHERE numStage=15;
INSERT INTO ob_etudiant SELECT 98,'nom108','prenom108',Ref(stage) FROM ob_stage stage WHERE numStage=41;
INSERT INTO ob_etudiant SELECT 99,'nom109','prenom109',Ref(stage) FROM ob_stage stage WHERE numStage=4;
INSERT INTO ob_etudiant SELECT 100,'nom110','prenom110',Ref(stage) FROM ob_stage stage WHERE numStage=5;
INSERT INTO ob_etudiant SELECT 101,'nom111','prenom111',Ref(stage) FROM ob_stage stage WHERE numStage=4;
INSERT INTO ob_etudiant SELECT 102,'nom112','prenom112',Ref(stage) FROM ob_stage stage WHERE numStage=32;
INSERT INTO ob_etudiant SELECT 103,'nom113','prenom113',Ref(stage) FROM ob_stage stage WHERE numStage=35;
INSERT INTO ob_etudiant SELECT 104,'nom114','prenom114',Ref(stage) FROM ob_stage stage WHERE numStage=32;
INSERT INTO ob_etudiant SELECT 105,'nom115','prenom115',Ref(stage) FROM ob_stage stage WHERE numStage=33;
INSERT INTO ob_etudiant SELECT 106,'nom116','prenom116',Ref(stage) FROM ob_stage stage WHERE numStage=13;
INSERT INTO ob_etudiant SELECT 107,'nom117','prenom117',Ref(stage) FROM ob_stage stage WHERE numStage=19;
INSERT INTO ob_etudiant SELECT 108,'nom118','prenom118',Ref(stage) FROM ob_stage stage WHERE numStage=20;
INSERT INTO ob_etudiant SELECT 109,'nom119','prenom119',Ref(stage) FROM ob_stage stage WHERE numStage=13;
INSERT INTO ob_etudiant SELECT 110,'nom120','prenom120',Ref(stage) FROM ob_stage stage WHERE numStage=43;
INSERT INTO ob_etudiant SELECT 111,'nom121','prenom121',Ref(stage) FROM ob_stage stage WHERE numStage=21;
INSERT INTO ob_etudiant SELECT 112,'nom122','prenom122',Ref(stage) FROM ob_stage stage WHERE numStage=40;
INSERT INTO ob_etudiant SELECT 113,'nom123','prenom123',Ref(stage) FROM ob_stage stage WHERE numStage=24;
INSERT INTO ob_etudiant SELECT 114,'nom124','prenom124',Ref(stage) FROM ob_stage stage WHERE numStage=36;
INSERT INTO ob_etudiant SELECT 115,'nom125','prenom125',Ref(stage) FROM ob_stage stage WHERE numStage=23;
INSERT INTO ob_etudiant SELECT 116,'nom126','prenom126',Ref(stage) FROM ob_stage stage WHERE numStage=9;
INSERT INTO ob_etudiant SELECT 117,'nom127','prenom127',Ref(stage) FROM ob_stage stage WHERE numStage=21;
INSERT INTO ob_etudiant SELECT 118,'nom128','prenom128',Ref(stage) FROM ob_stage stage WHERE numStage=25;
INSERT INTO ob_etudiant SELECT 119,'nom129','prenom129',Ref(stage) FROM ob_stage stage WHERE numStage=12;
INSERT INTO ob_etudiant SELECT 120,'nom130','prenom130',Ref(stage) FROM ob_stage stage WHERE numStage=38;
INSERT INTO ob_etudiant SELECT 121,'nom131','prenom131',Ref(stage) FROM ob_stage stage WHERE numStage=44;
INSERT INTO ob_etudiant SELECT 122,'nom132','prenom132',Ref(stage) FROM ob_stage stage WHERE numStage=38;
INSERT INTO ob_etudiant SELECT 123,'nom133','prenom133',Ref(stage) FROM ob_stage stage WHERE numStage=20;
INSERT INTO ob_etudiant SELECT 124,'nom134','prenom134',Ref(stage) FROM ob_stage stage WHERE numStage=29;
INSERT INTO ob_etudiant SELECT 125,'nom135','prenom135',Ref(stage) FROM ob_stage stage WHERE numStage=2;
INSERT INTO ob_etudiant SELECT 126,'nom136','prenom136',Ref(stage) FROM ob_stage stage WHERE numStage=10;
INSERT INTO ob_etudiant SELECT 127,'nom137','prenom137',Ref(stage) FROM ob_stage stage WHERE numStage=20;
INSERT INTO ob_etudiant SELECT 128,'nom138','prenom138',Ref(stage) FROM ob_stage stage WHERE numStage=41;
INSERT INTO ob_etudiant SELECT 129,'nom139','prenom139',Ref(stage) FROM ob_stage stage WHERE numStage=15;
INSERT INTO ob_etudiant SELECT 130,'nom140','prenom140',Ref(stage) FROM ob_stage stage WHERE numStage=14;
INSERT INTO ob_etudiant SELECT 131,'nom141','prenom141',Ref(stage) FROM ob_stage stage WHERE numStage=18;
INSERT INTO ob_etudiant SELECT 132,'nom142','prenom142',Ref(stage) FROM ob_stage stage WHERE numStage=22;
INSERT INTO ob_etudiant SELECT 133,'nom143','prenom143',Ref(stage) FROM ob_stage stage WHERE numStage=43;
INSERT INTO ob_etudiant SELECT 134,'nom144','prenom144',Ref(stage) FROM ob_stage stage WHERE numStage=15;
INSERT INTO ob_etudiant SELECT 135,'nom145','prenom145',Ref(stage) FROM ob_stage stage WHERE numStage=3;
INSERT INTO ob_etudiant SELECT 136,'nom146','prenom146',Ref(stage) FROM ob_stage stage WHERE numStage=29;
INSERT INTO ob_etudiant SELECT 137,'nom147','prenom147',Ref(stage) FROM ob_stage stage WHERE numStage=27;
INSERT INTO ob_etudiant SELECT 138,'nom148','prenom148',Ref(stage) FROM ob_stage stage WHERE numStage=5;
INSERT INTO ob_etudiant SELECT 139,'nom149','prenom149',Ref(stage) FROM ob_stage stage WHERE numStage=23;
INSERT INTO ob_etudiant SELECT 140,'nom150','prenom150',Ref(stage) FROM ob_stage stage WHERE numStage=25;
INSERT INTO ob_etudiant SELECT 141,'nom151','prenom151',Ref(stage) FROM ob_stage stage WHERE numStage=45;
INSERT INTO ob_etudiant SELECT 142,'nom152','prenom152',Ref(stage) FROM ob_stage stage WHERE numStage=15;
INSERT INTO ob_etudiant SELECT 143,'nom153','prenom153',Ref(stage) FROM ob_stage stage WHERE numStage=45;
INSERT INTO ob_etudiant SELECT 144,'nom154','prenom154',Ref(stage) FROM ob_stage stage WHERE numStage=35;
INSERT INTO ob_etudiant SELECT 145,'nom155','prenom155',Ref(stage) FROM ob_stage stage WHERE numStage=42;
INSERT INTO ob_etudiant SELECT 146,'nom156','prenom156',Ref(stage) FROM ob_stage stage WHERE numStage=16;
INSERT INTO ob_etudiant SELECT 147,'nom157','prenom157',Ref(stage) FROM ob_stage stage WHERE numStage=21;
INSERT INTO ob_etudiant SELECT 148,'nom158','prenom158',Ref(stage) FROM ob_stage stage WHERE numStage=13;
INSERT INTO ob_etudiant SELECT 149,'nom159','prenom159',Ref(stage) FROM ob_stage stage WHERE numStage=40;
INSERT INTO ob_etudiant SELECT 150,'nom160','prenom160',Ref(stage) FROM ob_stage stage WHERE numStage=48;
INSERT INTO ob_etudiant SELECT 151,'nom161','prenom161',Ref(stage) FROM ob_stage stage WHERE numStage=11;
INSERT INTO ob_etudiant SELECT 152,'nom162','prenom162',Ref(stage) FROM ob_stage stage WHERE numStage=30;
INSERT INTO ob_etudiant SELECT 153,'nom163','prenom163',Ref(stage) FROM ob_stage stage WHERE numStage=1;
INSERT INTO ob_etudiant SELECT 154,'nom164','prenom164',Ref(stage) FROM ob_stage stage WHERE numStage=2;
INSERT INTO ob_etudiant SELECT 155,'nom165','prenom165',Ref(stage) FROM ob_stage stage WHERE numStage=46;
INSERT INTO ob_etudiant SELECT 156,'nom166','prenom166',Ref(stage) FROM ob_stage stage WHERE numStage=44;
INSERT INTO ob_etudiant SELECT 157,'nom167','prenom167',Ref(stage) FROM ob_stage stage WHERE numStage=12;
INSERT INTO ob_etudiant SELECT 158,'nom168','prenom168',Ref(stage) FROM ob_stage stage WHERE numStage=20;
INSERT INTO ob_etudiant SELECT 159,'nom169','prenom169',Ref(stage) FROM ob_stage stage WHERE numStage=10;
INSERT INTO ob_etudiant SELECT 160,'nom170','prenom170',Ref(stage) FROM ob_stage stage WHERE numStage=44;
INSERT INTO ob_etudiant SELECT 161,'nom171','prenom171',Ref(stage) FROM ob_stage stage WHERE numStage=1;
INSERT INTO ob_etudiant SELECT 162,'nom172','prenom172',Ref(stage) FROM ob_stage stage WHERE numStage=44;
INSERT INTO ob_etudiant SELECT 163,'nom173','prenom173',Ref(stage) FROM ob_stage stage WHERE numStage=23;
INSERT INTO ob_etudiant SELECT 164,'nom174','prenom174',Ref(stage) FROM ob_stage stage WHERE numStage=4;
INSERT INTO ob_etudiant SELECT 165,'nom175','prenom175',Ref(stage) FROM ob_stage stage WHERE numStage=23;
INSERT INTO ob_etudiant SELECT 166,'nom176','prenom176',Ref(stage) FROM ob_stage stage WHERE numStage=17;
INSERT INTO ob_etudiant SELECT 167,'nom177','prenom177',Ref(stage) FROM ob_stage stage WHERE numStage=29;
INSERT INTO ob_etudiant SELECT 168,'nom178','prenom178',Ref(stage) FROM ob_stage stage WHERE numStage=17;
INSERT INTO ob_etudiant SELECT 169,'nom179','prenom179',Ref(stage) FROM ob_stage stage WHERE numStage=41;
INSERT INTO ob_etudiant SELECT 170,'nom180','prenom180',Ref(stage) FROM ob_stage stage WHERE numStage=42;
INSERT INTO ob_etudiant SELECT 171,'nom181','prenom181',Ref(stage) FROM ob_stage stage WHERE numStage=43;
INSERT INTO ob_etudiant SELECT 172,'nom182','prenom182',Ref(stage) FROM ob_stage stage WHERE numStage=27;
INSERT INTO ob_etudiant SELECT 173,'nom183','prenom183',Ref(stage) FROM ob_stage stage WHERE numStage=33;
INSERT INTO ob_etudiant SELECT 174,'nom184','prenom184',Ref(stage) FROM ob_stage stage WHERE numStage=12;
INSERT INTO ob_etudiant SELECT 175,'nom185','prenom185',Ref(stage) FROM ob_stage stage WHERE numStage=6;
INSERT INTO ob_etudiant SELECT 176,'nom186','prenom186',Ref(stage) FROM ob_stage stage WHERE numStage=38;
INSERT INTO ob_etudiant SELECT 177,'nom187','prenom187',Ref(stage) FROM ob_stage stage WHERE numStage=40;
INSERT INTO ob_etudiant SELECT 178,'nom188','prenom188',Ref(stage) FROM ob_stage stage WHERE numStage=4;
INSERT INTO ob_etudiant SELECT 179,'nom189','prenom189',Ref(stage) FROM ob_stage stage WHERE numStage=44;
INSERT INTO ob_etudiant SELECT 180,'nom190','prenom190',Ref(stage) FROM ob_stage stage WHERE numStage=9;
INSERT INTO ob_etudiant SELECT 181,'nom191','prenom191',Ref(stage) FROM ob_stage stage WHERE numStage=16;
INSERT INTO ob_etudiant SELECT 182,'nom192','prenom192',Ref(stage) FROM ob_stage stage WHERE numStage=5;
INSERT INTO ob_etudiant SELECT 183,'nom193','prenom193',Ref(stage) FROM ob_stage stage WHERE numStage=20;
INSERT INTO ob_etudiant SELECT 184,'nom194','prenom194',Ref(stage) FROM ob_stage stage WHERE numStage=47;
INSERT INTO ob_etudiant SELECT 185,'nom195','prenom195',Ref(stage) FROM ob_stage stage WHERE numStage=14;
INSERT INTO ob_etudiant SELECT 186,'nom196','prenom196',Ref(stage) FROM ob_stage stage WHERE numStage=18;
INSERT INTO ob_etudiant SELECT 187,'nom197','prenom197',Ref(stage) FROM ob_stage stage WHERE numStage=22;
INSERT INTO ob_etudiant SELECT 188,'nom198','prenom198',Ref(stage) FROM ob_stage stage WHERE numStage=17;
INSERT INTO ob_etudiant SELECT 189,'nom199','prenom199',Ref(stage) FROM ob_stage stage WHERE numStage=20;
INSERT INTO ob_etudiant SELECT 190,'nom200','prenom200',Ref(stage) FROM ob_stage stage WHERE numStage=46;
INSERT INTO ob_etudiant SELECT 191,'nom201','prenom201',Ref(stage) FROM ob_stage stage WHERE numStage=23;
INSERT INTO ob_etudiant SELECT 192,'nom202','prenom202',Ref(stage) FROM ob_stage stage WHERE numStage=23;
INSERT INTO ob_etudiant SELECT 193,'nom203','prenom203',Ref(stage) FROM ob_stage stage WHERE numStage=4;
INSERT INTO ob_etudiant SELECT 194,'nom204','prenom204',Ref(stage) FROM ob_stage stage WHERE numStage=18;
INSERT INTO ob_etudiant SELECT 195,'nom205','prenom205',Ref(stage) FROM ob_stage stage WHERE numStage=8;
INSERT INTO ob_etudiant SELECT 196,'nom206','prenom206',Ref(stage) FROM ob_stage stage WHERE numStage=12;
INSERT INTO ob_etudiant SELECT 197,'nom207','prenom207',Ref(stage) FROM ob_stage stage WHERE numStage=17;
INSERT INTO ob_etudiant SELECT 198,'nom208','prenom208',Ref(stage) FROM ob_stage stage WHERE numStage=32;
INSERT INTO ob_etudiant SELECT 199,'nom209','prenom209',Ref(stage) FROM ob_stage stage WHERE numStage=15;
INSERT INTO ob_etudiant SELECT 200,'nom210','prenom210',Ref(stage) FROM ob_stage stage WHERE numStage=5;
INSERT INTO ob_etudiant SELECT 201,'nom211','prenom211',Ref(stage) FROM ob_stage stage WHERE numStage=4;
INSERT INTO ob_etudiant SELECT 202,'nom212','prenom212',Ref(stage) FROM ob_stage stage WHERE numStage=39;
INSERT INTO ob_etudiant SELECT 203,'nom213','prenom213',Ref(stage) FROM ob_stage stage WHERE numStage=3;
INSERT INTO ob_etudiant SELECT 204,'nom214','prenom214',Ref(stage) FROM ob_stage stage WHERE numStage=18;
INSERT INTO ob_etudiant SELECT 205,'nom215','prenom215',Ref(stage) FROM ob_stage stage WHERE numStage=40;
INSERT INTO ob_etudiant SELECT 206,'nom216','prenom216',Ref(stage) FROM ob_stage stage WHERE numStage=6;
INSERT INTO ob_etudiant SELECT 207,'nom217','prenom217',Ref(stage) FROM ob_stage stage WHERE numStage=8;
INSERT INTO ob_etudiant SELECT 208,'nom218','prenom218',Ref(stage) FROM ob_stage stage WHERE numStage=24;
INSERT INTO ob_etudiant SELECT 209,'nom219','prenom219',Ref(stage) FROM ob_stage stage WHERE numStage=17;
INSERT INTO ob_etudiant SELECT 210,'nom220','prenom220',Ref(stage) FROM ob_stage stage WHERE numStage=24;
INSERT INTO ob_etudiant SELECT 211,'nom221','prenom221',Ref(stage) FROM ob_stage stage WHERE numStage=37;
INSERT INTO ob_etudiant SELECT 212,'nom222','prenom222',Ref(stage) FROM ob_stage stage WHERE numStage=4;
INSERT INTO ob_etudiant SELECT 213,'nom223','prenom223',Ref(stage) FROM ob_stage stage WHERE numStage=4;
INSERT INTO ob_etudiant SELECT 214,'nom224','prenom224',Ref(stage) FROM ob_stage stage WHERE numStage=19;
INSERT INTO ob_etudiant SELECT 215,'nom225','prenom225',Ref(stage) FROM ob_stage stage WHERE numStage=41;
INSERT INTO ob_etudiant SELECT 216,'nom226','prenom226',Ref(stage) FROM ob_stage stage WHERE numStage=35;
INSERT INTO ob_etudiant SELECT 217,'nom227','prenom227',Ref(stage) FROM ob_stage stage WHERE numStage=42;
INSERT INTO ob_etudiant SELECT 218,'nom228','prenom228',Ref(stage) FROM ob_stage stage WHERE numStage=23;
INSERT INTO ob_etudiant SELECT 219,'nom229','prenom229',Ref(stage) FROM ob_stage stage WHERE numStage=43;
INSERT INTO ob_etudiant SELECT 220,'nom230','prenom230',Ref(stage) FROM ob_stage stage WHERE numStage=20;
INSERT INTO ob_etudiant SELECT 221,'nom231','prenom231',Ref(stage) FROM ob_stage stage WHERE numStage=4;
INSERT INTO ob_etudiant SELECT 222,'nom232','prenom232',Ref(stage) FROM ob_stage stage WHERE numStage=10;
INSERT INTO ob_etudiant SELECT 223,'nom233','prenom233',Ref(stage) FROM ob_stage stage WHERE numStage=43;
INSERT INTO ob_etudiant SELECT 224,'nom234','prenom234',Ref(stage) FROM ob_stage stage WHERE numStage=12;
INSERT INTO ob_etudiant SELECT 225,'nom235','prenom235',Ref(stage) FROM ob_stage stage WHERE numStage=11;
INSERT INTO ob_etudiant SELECT 226,'nom236','prenom236',Ref(stage) FROM ob_stage stage WHERE numStage=36;
INSERT INTO ob_etudiant SELECT 227,'nom237','prenom237',Ref(stage) FROM ob_stage stage WHERE numStage=20;
INSERT INTO ob_etudiant SELECT 228,'nom238','prenom238',Ref(stage) FROM ob_stage stage WHERE numStage=6;
INSERT INTO ob_etudiant SELECT 229,'nom239','prenom239',Ref(stage) FROM ob_stage stage WHERE numStage=42;
INSERT INTO ob_etudiant SELECT 230,'nom240','prenom240',Ref(stage) FROM ob_stage stage WHERE numStage=30;
INSERT INTO ob_etudiant SELECT 231,'nom241','prenom241',Ref(stage) FROM ob_stage stage WHERE numStage=27;
INSERT INTO ob_etudiant SELECT 232,'nom242','prenom242',Ref(stage) FROM ob_stage stage WHERE numStage=12;
INSERT INTO ob_etudiant SELECT 233,'nom243','prenom243',Ref(stage) FROM ob_stage stage WHERE numStage=5;
INSERT INTO ob_etudiant SELECT 234,'nom244','prenom244',Ref(stage) FROM ob_stage stage WHERE numStage=3;
INSERT INTO ob_etudiant SELECT 235,'nom245','prenom245',Ref(stage) FROM ob_stage stage WHERE numStage=17;
INSERT INTO ob_etudiant SELECT 236,'nom246','prenom246',Ref(stage) FROM ob_stage stage WHERE numStage=34;
INSERT INTO ob_etudiant SELECT 237,'nom247','prenom247',Ref(stage) FROM ob_stage stage WHERE numStage=1;
INSERT INTO ob_etudiant SELECT 238,'nom248','prenom248',Ref(stage) FROM ob_stage stage WHERE numStage=10;
INSERT INTO ob_etudiant SELECT 239,'nom249','prenom249',Ref(stage) FROM ob_stage stage WHERE numStage=43;
INSERT INTO ob_etudiant SELECT 240,'nom250','prenom250',Ref(stage) FROM ob_stage stage WHERE numStage=27;
INSERT INTO ob_etudiant SELECT 241,'nom251','prenom251',Ref(stage) FROM ob_stage stage WHERE numStage=39;
INSERT INTO ob_etudiant SELECT 242,'nom252','prenom252',Ref(stage) FROM ob_stage stage WHERE numStage=23;
INSERT INTO ob_etudiant SELECT 243,'nom253','prenom253',Ref(stage) FROM ob_stage stage WHERE numStage=42;
INSERT INTO ob_etudiant SELECT 244,'nom254','prenom254',Ref(stage) FROM ob_stage stage WHERE numStage=13;
INSERT INTO ob_etudiant SELECT 245,'nom255','prenom255',Ref(stage) FROM ob_stage stage WHERE numStage=33;
INSERT INTO ob_etudiant SELECT 246,'nom256','prenom256',Ref(stage) FROM ob_stage stage WHERE numStage=41;
INSERT INTO ob_etudiant SELECT 247,'nom257','prenom257',Ref(stage) FROM ob_stage stage WHERE numStage=19;
INSERT INTO ob_etudiant SELECT 248,'nom258','prenom258',Ref(stage) FROM ob_stage stage WHERE numStage=30;
INSERT INTO ob_etudiant SELECT 249,'nom259','prenom259',Ref(stage) FROM ob_stage stage WHERE numStage=29;
INSERT INTO ob_etudiant SELECT 250,'nom260','prenom260',Ref(stage) FROM ob_stage stage WHERE numStage=25;
INSERT INTO ob_etudiant SELECT 251,'nom261','prenom261',Ref(stage) FROM ob_stage stage WHERE numStage=35;
INSERT INTO ob_etudiant SELECT 252,'nom262','prenom262',Ref(stage) FROM ob_stage stage WHERE numStage=44;
INSERT INTO ob_etudiant SELECT 253,'nom263','prenom263',Ref(stage) FROM ob_stage stage WHERE numStage=5;
INSERT INTO ob_etudiant SELECT 254,'nom264','prenom264',Ref(stage) FROM ob_stage stage WHERE numStage=39;
INSERT INTO ob_etudiant SELECT 255,'nom265','prenom265',Ref(stage) FROM ob_stage stage WHERE numStage=2;
INSERT INTO ob_etudiant SELECT 256,'nom266','prenom266',Ref(stage) FROM ob_stage stage WHERE numStage=41;
INSERT INTO ob_etudiant SELECT 257,'nom267','prenom267',Ref(stage) FROM ob_stage stage WHERE numStage=23;
INSERT INTO ob_etudiant SELECT 258,'nom268','prenom268',Ref(stage) FROM ob_stage stage WHERE numStage=21;
INSERT INTO ob_etudiant SELECT 259,'nom269','prenom269',Ref(stage) FROM ob_stage stage WHERE numStage=30;
INSERT INTO ob_etudiant SELECT 260,'nom270','prenom270',Ref(stage) FROM ob_stage stage WHERE numStage=20;
INSERT INTO ob_etudiant SELECT 261,'nom271','prenom271',Ref(stage) FROM ob_stage stage WHERE numStage=8;
INSERT INTO ob_etudiant SELECT 262,'nom272','prenom272',Ref(stage) FROM ob_stage stage WHERE numStage=2;
INSERT INTO ob_etudiant SELECT 263,'nom273','prenom273',Ref(stage) FROM ob_stage stage WHERE numStage=34;
INSERT INTO ob_etudiant SELECT 264,'nom274','prenom274',Ref(stage) FROM ob_stage stage WHERE numStage=34;
INSERT INTO ob_etudiant SELECT 265,'nom275','prenom275',Ref(stage) FROM ob_stage stage WHERE numStage=25;
INSERT INTO ob_etudiant SELECT 266,'nom276','prenom276',Ref(stage) FROM ob_stage stage WHERE numStage=37;
INSERT INTO ob_etudiant SELECT 267,'nom277','prenom277',Ref(stage) FROM ob_stage stage WHERE numStage=42;
INSERT INTO ob_etudiant SELECT 268,'nom278','prenom278',Ref(stage) FROM ob_stage stage WHERE numStage=12;
INSERT INTO ob_etudiant SELECT 269,'nom279','prenom279',Ref(stage) FROM ob_stage stage WHERE numStage=32;
INSERT INTO ob_etudiant SELECT 270,'nom280','prenom280',Ref(stage) FROM ob_stage stage WHERE numStage=30;
INSERT INTO ob_etudiant SELECT 271,'nom281','prenom281',Ref(stage) FROM ob_stage stage WHERE numStage=2;
INSERT INTO ob_etudiant SELECT 272,'nom282','prenom282',Ref(stage) FROM ob_stage stage WHERE numStage=20;
INSERT INTO ob_etudiant SELECT 273,'nom283','prenom283',Ref(stage) FROM ob_stage stage WHERE numStage=6;
INSERT INTO ob_etudiant SELECT 274,'nom284','prenom284',Ref(stage) FROM ob_stage stage WHERE numStage=8;
INSERT INTO ob_etudiant SELECT 275,'nom285','prenom285',Ref(stage) FROM ob_stage stage WHERE numStage=27;
INSERT INTO ob_etudiant SELECT 276,'nom286','prenom286',Ref(stage) FROM ob_stage stage WHERE numStage=9;
INSERT INTO ob_etudiant SELECT 277,'nom287','prenom287',Ref(stage) FROM ob_stage stage WHERE numStage=12;
INSERT INTO ob_etudiant SELECT 278,'nom288','prenom288',Ref(stage) FROM ob_stage stage WHERE numStage=45;
INSERT INTO ob_etudiant SELECT 279,'nom289','prenom289',Ref(stage) FROM ob_stage stage WHERE numStage=30;
INSERT INTO ob_etudiant SELECT 280,'nom290','prenom290',Ref(stage) FROM ob_stage stage WHERE numStage=33;
INSERT INTO ob_etudiant SELECT 281,'nom291','prenom291',Ref(stage) FROM ob_stage stage WHERE numStage=41;
INSERT INTO ob_etudiant SELECT 282,'nom292','prenom292',Ref(stage) FROM ob_stage stage WHERE numStage=5;
INSERT INTO ob_etudiant SELECT 283,'nom293','prenom293',Ref(stage) FROM ob_stage stage WHERE numStage=48;
INSERT INTO ob_etudiant SELECT 284,'nom294','prenom294',Ref(stage) FROM ob_stage stage WHERE numStage=4;
INSERT INTO ob_etudiant SELECT 285,'nom295','prenom295',Ref(stage) FROM ob_stage stage WHERE numStage=5;
INSERT INTO ob_etudiant SELECT 286,'nom296','prenom296',Ref(stage) FROM ob_stage stage WHERE numStage=44;
INSERT INTO ob_etudiant SELECT 287,'nom297','prenom297',Ref(stage) FROM ob_stage stage WHERE numStage=43;
INSERT INTO ob_etudiant SELECT 288,'nom298','prenom298',Ref(stage) FROM ob_stage stage WHERE numStage=17;
INSERT INTO ob_etudiant SELECT 289,'nom299','prenom299',Ref(stage) FROM ob_stage stage WHERE numStage=16;
INSERT INTO ob_etudiant SELECT 290,'nom300','prenom300',Ref(stage) FROM ob_stage stage WHERE numStage=9;
INSERT INTO ob_etudiant SELECT 291,'nom301','prenom301',Ref(stage) FROM ob_stage stage WHERE numStage=11;
INSERT INTO ob_etudiant SELECT 292,'nom302','prenom302',Ref(stage) FROM ob_stage stage WHERE numStage=25;
INSERT INTO ob_etudiant SELECT 293,'nom303','prenom303',Ref(stage) FROM ob_stage stage WHERE numStage=3;
INSERT INTO ob_etudiant SELECT 294,'nom304','prenom304',Ref(stage) FROM ob_stage stage WHERE numStage=18;
INSERT INTO ob_etudiant SELECT 295,'nom305','prenom305',Ref(stage) FROM ob_stage stage WHERE numStage=48;
INSERT INTO ob_etudiant SELECT 296,'nom306','prenom306',Ref(stage) FROM ob_stage stage WHERE numStage=27;
INSERT INTO ob_etudiant SELECT 297,'nom307','prenom307',Ref(stage) FROM ob_stage stage WHERE numStage=30;
INSERT INTO ob_etudiant SELECT 298,'nom308','prenom308',Ref(stage) FROM ob_stage stage WHERE numStage=7;
INSERT INTO ob_etudiant SELECT 299,'nom309','prenom309',Ref(stage) FROM ob_stage stage WHERE numStage=30;
INSERT INTO ob_etudiant SELECT 300,'nom310','prenom310',Ref(stage) FROM ob_stage stage WHERE numStage=26;
INSERT INTO ob_etudiant SELECT 301,'nom311','prenom311',Ref(stage) FROM ob_stage stage WHERE numStage=25;
INSERT INTO ob_etudiant SELECT 302,'nom312','prenom312',Ref(stage) FROM ob_stage stage WHERE numStage=25;
INSERT INTO ob_etudiant SELECT 303,'nom313','prenom313',Ref(stage) FROM ob_stage stage WHERE numStage=30;
INSERT INTO ob_etudiant SELECT 304,'nom314','prenom314',Ref(stage) FROM ob_stage stage WHERE numStage=34;
INSERT INTO ob_etudiant SELECT 305,'nom315','prenom315',Ref(stage) FROM ob_stage stage WHERE numStage=11;
INSERT INTO ob_etudiant SELECT 306,'nom316','prenom316',Ref(stage) FROM ob_stage stage WHERE numStage=15;
INSERT INTO ob_etudiant SELECT 307,'nom317','prenom317',Ref(stage) FROM ob_stage stage WHERE numStage=14;
INSERT INTO ob_etudiant SELECT 308,'nom318','prenom318',Ref(stage) FROM ob_stage stage WHERE numStage=23;
INSERT INTO ob_etudiant SELECT 309,'nom319','prenom319',Ref(stage) FROM ob_stage stage WHERE numStage=20;
INSERT INTO ob_etudiant SELECT 310,'nom320','prenom320',Ref(stage) FROM ob_stage stage WHERE numStage=43;
INSERT INTO ob_etudiant SELECT 311,'nom321','prenom321',Ref(stage) FROM ob_stage stage WHERE numStage=33;
INSERT INTO ob_etudiant SELECT 312,'nom322','prenom322',Ref(stage) FROM ob_stage stage WHERE numStage=45;
INSERT INTO ob_etudiant SELECT 313,'nom323','prenom323',Ref(stage) FROM ob_stage stage WHERE numStage=19;
INSERT INTO ob_etudiant SELECT 314,'nom324','prenom324',Ref(stage) FROM ob_stage stage WHERE numStage=31;
INSERT INTO ob_etudiant SELECT 315,'nom325','prenom325',Ref(stage) FROM ob_stage stage WHERE numStage=26;
INSERT INTO ob_etudiant SELECT 316,'nom326','prenom326',Ref(stage) FROM ob_stage stage WHERE numStage=32;
INSERT INTO ob_etudiant SELECT 317,'nom327','prenom327',Ref(stage) FROM ob_stage stage WHERE numStage=9;
INSERT INTO ob_etudiant SELECT 318,'nom328','prenom328',Ref(stage) FROM ob_stage stage WHERE numStage=16;
INSERT INTO ob_etudiant SELECT 319,'nom329','prenom329',Ref(stage) FROM ob_stage stage WHERE numStage=9;
INSERT INTO ob_etudiant SELECT 320,'nom330','prenom330',Ref(stage) FROM ob_stage stage WHERE numStage=2;
INSERT INTO ob_etudiant SELECT 321,'nom331','prenom331',Ref(stage) FROM ob_stage stage WHERE numStage=14;
INSERT INTO ob_etudiant SELECT 322,'nom332','prenom332',Ref(stage) FROM ob_stage stage WHERE numStage=29;
INSERT INTO ob_etudiant SELECT 323,'nom333','prenom333',Ref(stage) FROM ob_stage stage WHERE numStage=22;
INSERT INTO ob_etudiant SELECT 324,'nom334','prenom334',Ref(stage) FROM ob_stage stage WHERE numStage=35;
INSERT INTO ob_etudiant SELECT 325,'nom335','prenom335',Ref(stage) FROM ob_stage stage WHERE numStage=22;
INSERT INTO ob_etudiant SELECT 326,'nom336','prenom336',Ref(stage) FROM ob_stage stage WHERE numStage=4;
INSERT INTO ob_etudiant SELECT 327,'nom337','prenom337',Ref(stage) FROM ob_stage stage WHERE numStage=26;
INSERT INTO ob_etudiant SELECT 328,'nom338','prenom338',Ref(stage) FROM ob_stage stage WHERE numStage=35;
INSERT INTO ob_etudiant SELECT 329,'nom339','prenom339',Ref(stage) FROM ob_stage stage WHERE numStage=23;
INSERT INTO ob_etudiant SELECT 330,'nom340','prenom340',Ref(stage) FROM ob_stage stage WHERE numStage=46;
INSERT INTO ob_etudiant SELECT 331,'nom341','prenom341',Ref(stage) FROM ob_stage stage WHERE numStage=42;
INSERT INTO ob_etudiant SELECT 332,'nom342','prenom342',Ref(stage) FROM ob_stage stage WHERE numStage=22;
INSERT INTO ob_etudiant SELECT 333,'nom343','prenom343',Ref(stage) FROM ob_stage stage WHERE numStage=28;
INSERT INTO ob_etudiant SELECT 334,'nom344','prenom344',Ref(stage) FROM ob_stage stage WHERE numStage=31;
INSERT INTO ob_etudiant SELECT 335,'nom345','prenom345',Ref(stage) FROM ob_stage stage WHERE numStage=27;
INSERT INTO ob_etudiant SELECT 336,'nom346','prenom346',Ref(stage) FROM ob_stage stage WHERE numStage=14;
INSERT INTO ob_etudiant SELECT 337,'nom347','prenom347',Ref(stage) FROM ob_stage stage WHERE numStage=33;
INSERT INTO ob_etudiant SELECT 338,'nom348','prenom348',Ref(stage) FROM ob_stage stage WHERE numStage=35;
INSERT INTO ob_etudiant SELECT 339,'nom349','prenom349',Ref(stage) FROM ob_stage stage WHERE numStage=30;
INSERT INTO ob_etudiant SELECT 340,'nom350','prenom350',Ref(stage) FROM ob_stage stage WHERE numStage=22;
INSERT INTO ob_etudiant SELECT 341,'nom351','prenom351',Ref(stage) FROM ob_stage stage WHERE numStage=46;
INSERT INTO ob_etudiant SELECT 342,'nom352','prenom352',Ref(stage) FROM ob_stage stage WHERE numStage=15;
INSERT INTO ob_etudiant SELECT 343,'nom353','prenom353',Ref(stage) FROM ob_stage stage WHERE numStage=26;
INSERT INTO ob_etudiant SELECT 344,'nom354','prenom354',Ref(stage) FROM ob_stage stage WHERE numStage=11;
INSERT INTO ob_etudiant SELECT 345,'nom355','prenom355',Ref(stage) FROM ob_stage stage WHERE numStage=31;
INSERT INTO ob_etudiant SELECT 346,'nom356','prenom356',Ref(stage) FROM ob_stage stage WHERE numStage=47;
INSERT INTO ob_etudiant SELECT 347,'nom357','prenom357',Ref(stage) FROM ob_stage stage WHERE numStage=19;
INSERT INTO ob_etudiant SELECT 348,'nom358','prenom358',Ref(stage) FROM ob_stage stage WHERE numStage=24;
INSERT INTO ob_etudiant SELECT 349,'nom359','prenom359',Ref(stage) FROM ob_stage stage WHERE numStage=3;
INSERT INTO ob_etudiant SELECT 350,'nom360','prenom360',Ref(stage) FROM ob_stage stage WHERE numStage=17;
INSERT INTO ob_etudiant SELECT 351,'nom361','prenom361',Ref(stage) FROM ob_stage stage WHERE numStage=11;
INSERT INTO ob_etudiant SELECT 352,'nom362','prenom362',Ref(stage) FROM ob_stage stage WHERE numStage=14;
INSERT INTO ob_etudiant SELECT 353,'nom363','prenom363',Ref(stage) FROM ob_stage stage WHERE numStage=33;
INSERT INTO ob_etudiant SELECT 354,'nom364','prenom364',Ref(stage) FROM ob_stage stage WHERE numStage=34;
INSERT INTO ob_etudiant SELECT 355,'nom365','prenom365',Ref(stage) FROM ob_stage stage WHERE numStage=22;
INSERT INTO ob_etudiant SELECT 356,'nom366','prenom366',Ref(stage) FROM ob_stage stage WHERE numStage=38;
INSERT INTO ob_etudiant SELECT 357,'nom367','prenom367',Ref(stage) FROM ob_stage stage WHERE numStage=42;
INSERT INTO ob_etudiant SELECT 358,'nom368','prenom368',Ref(stage) FROM ob_stage stage WHERE numStage=14;
INSERT INTO ob_etudiant SELECT 359,'nom369','prenom369',Ref(stage) FROM ob_stage stage WHERE numStage=36;
INSERT INTO ob_etudiant SELECT 360,'nom370','prenom370',Ref(stage) FROM ob_stage stage WHERE numStage=4;
INSERT INTO ob_etudiant SELECT 361,'nom371','prenom371',Ref(stage) FROM ob_stage stage WHERE numStage=12;
INSERT INTO ob_etudiant SELECT 362,'nom372','prenom372',Ref(stage) FROM ob_stage stage WHERE numStage=11;
INSERT INTO ob_etudiant SELECT 363,'nom373','prenom373',Ref(stage) FROM ob_stage stage WHERE numStage=33;
INSERT INTO ob_etudiant SELECT 364,'nom374','prenom374',Ref(stage) FROM ob_stage stage WHERE numStage=32;
INSERT INTO ob_etudiant SELECT 365,'nom375','prenom375',Ref(stage) FROM ob_stage stage WHERE numStage=13;
INSERT INTO ob_etudiant SELECT 366,'nom376','prenom376',Ref(stage) FROM ob_stage stage WHERE numStage=46;
INSERT INTO ob_etudiant SELECT 367,'nom377','prenom377',Ref(stage) FROM ob_stage stage WHERE numStage=29;
INSERT INTO ob_etudiant SELECT 368,'nom378','prenom378',Ref(stage) FROM ob_stage stage WHERE numStage=11;
INSERT INTO ob_etudiant SELECT 369,'nom379','prenom379',Ref(stage) FROM ob_stage stage WHERE numStage=28;
INSERT INTO ob_etudiant SELECT 370,'nom380','prenom380',Ref(stage) FROM ob_stage stage WHERE numStage=5;
INSERT INTO ob_etudiant SELECT 371,'nom381','prenom381',Ref(stage) FROM ob_stage stage WHERE numStage=14;
INSERT INTO ob_etudiant SELECT 372,'nom382','prenom382',Ref(stage) FROM ob_stage stage WHERE numStage=35;
INSERT INTO ob_etudiant SELECT 373,'nom383','prenom383',Ref(stage) FROM ob_stage stage WHERE numStage=19;
INSERT INTO ob_etudiant SELECT 374,'nom384','prenom384',Ref(stage) FROM ob_stage stage WHERE numStage=42;
INSERT INTO ob_etudiant SELECT 375,'nom385','prenom385',Ref(stage) FROM ob_stage stage WHERE numStage=19;
INSERT INTO ob_etudiant SELECT 376,'nom386','prenom386',Ref(stage) FROM ob_stage stage WHERE numStage=27;
INSERT INTO ob_etudiant SELECT 377,'nom387','prenom387',Ref(stage) FROM ob_stage stage WHERE numStage=7;
INSERT INTO ob_etudiant SELECT 378,'nom388','prenom388',Ref(stage) FROM ob_stage stage WHERE numStage=4;
INSERT INTO ob_etudiant SELECT 379,'nom389','prenom389',Ref(stage) FROM ob_stage stage WHERE numStage=32;
INSERT INTO ob_etudiant SELECT 380,'nom390','prenom390',Ref(stage) FROM ob_stage stage WHERE numStage=6;
INSERT INTO ob_etudiant SELECT 381,'nom391','prenom391',Ref(stage) FROM ob_stage stage WHERE numStage=8;
INSERT INTO ob_etudiant SELECT 382,'nom392','prenom392',Ref(stage) FROM ob_stage stage WHERE numStage=19;
INSERT INTO ob_etudiant SELECT 383,'nom393','prenom393',Ref(stage) FROM ob_stage stage WHERE numStage=46;
INSERT INTO ob_etudiant SELECT 384,'nom394','prenom394',Ref(stage) FROM ob_stage stage WHERE numStage=46;
INSERT INTO ob_etudiant SELECT 385,'nom395','prenom395',Ref(stage) FROM ob_stage stage WHERE numStage=33;
INSERT INTO ob_etudiant SELECT 386,'nom396','prenom396',Ref(stage) FROM ob_stage stage WHERE numStage=39;
INSERT INTO ob_etudiant SELECT 387,'nom397','prenom397',Ref(stage) FROM ob_stage stage WHERE numStage=22;
INSERT INTO ob_etudiant SELECT 388,'nom398','prenom398',Ref(stage) FROM ob_stage stage WHERE numStage=30;
INSERT INTO ob_etudiant SELECT 389,'nom399','prenom399',Ref(stage) FROM ob_stage stage WHERE numStage=14;
INSERT INTO ob_etudiant SELECT 390,'nom400','prenom400',Ref(stage) FROM ob_stage stage WHERE numStage=36;
INSERT INTO ob_etudiant SELECT 391,'nom401','prenom401',Ref(stage) FROM ob_stage stage WHERE numStage=39;
INSERT INTO ob_etudiant SELECT 392,'nom402','prenom402',Ref(stage) FROM ob_stage stage WHERE numStage=38;
INSERT INTO ob_etudiant SELECT 393,'nom403','prenom403',Ref(stage) FROM ob_stage stage WHERE numStage=39;
INSERT INTO ob_etudiant SELECT 394,'nom404','prenom404',Ref(stage) FROM ob_stage stage WHERE numStage=10;
INSERT INTO ob_etudiant SELECT 395,'nom405','prenom405',Ref(stage) FROM ob_stage stage WHERE numStage=44;
INSERT INTO ob_etudiant SELECT 396,'nom406','prenom406',Ref(stage) FROM ob_stage stage WHERE numStage=28;
INSERT INTO ob_etudiant SELECT 397,'nom407','prenom407',Ref(stage) FROM ob_stage stage WHERE numStage=33;
INSERT INTO ob_etudiant SELECT 398,'nom408','prenom408',Ref(stage) FROM ob_stage stage WHERE numStage=33;
INSERT INTO ob_etudiant SELECT 399,'nom409','prenom409',Ref(stage) FROM ob_stage stage WHERE numStage=19;
INSERT INTO ob_etudiant SELECT 400,'nom410','prenom410',Ref(stage) FROM ob_stage stage WHERE numStage=11;
INSERT INTO ob_etudiant SELECT 401,'nom411','prenom411',Ref(stage) FROM ob_stage stage WHERE numStage=36;
INSERT INTO ob_etudiant SELECT 402,'nom412','prenom412',Ref(stage) FROM ob_stage stage WHERE numStage=46;
INSERT INTO ob_etudiant SELECT 403,'nom413','prenom413',Ref(stage) FROM ob_stage stage WHERE numStage=35;
INSERT INTO ob_etudiant SELECT 404,'nom414','prenom414',Ref(stage) FROM ob_stage stage WHERE numStage=3;
INSERT INTO ob_etudiant SELECT 405,'nom415','prenom415',Ref(stage) FROM ob_stage stage WHERE numStage=43;
INSERT INTO ob_etudiant SELECT 406,'nom416','prenom416',Ref(stage) FROM ob_stage stage WHERE numStage=20;
INSERT INTO ob_etudiant SELECT 407,'nom417','prenom417',Ref(stage) FROM ob_stage stage WHERE numStage=20;
INSERT INTO ob_etudiant SELECT 408,'nom418','prenom418',Ref(stage) FROM ob_stage stage WHERE numStage=19;
INSERT INTO ob_etudiant SELECT 409,'nom419','prenom419',Ref(stage) FROM ob_stage stage WHERE numStage=15;
INSERT INTO ob_etudiant SELECT 410,'nom420','prenom420',Ref(stage) FROM ob_stage stage WHERE numStage=12;
INSERT INTO ob_etudiant SELECT 411,'nom421','prenom421',Ref(stage) FROM ob_stage stage WHERE numStage=20;
INSERT INTO ob_etudiant SELECT 412,'nom422','prenom422',Ref(stage) FROM ob_stage stage WHERE numStage=38;
INSERT INTO ob_etudiant SELECT 413,'nom423','prenom423',Ref(stage) FROM ob_stage stage WHERE numStage=9;
INSERT INTO ob_etudiant SELECT 414,'nom424','prenom424',Ref(stage) FROM ob_stage stage WHERE numStage=14;
INSERT INTO ob_etudiant SELECT 415,'nom425','prenom425',Ref(stage) FROM ob_stage stage WHERE numStage=6;
INSERT INTO ob_etudiant SELECT 416,'nom426','prenom426',Ref(stage) FROM ob_stage stage WHERE numStage=36;
INSERT INTO ob_etudiant SELECT 417,'nom427','prenom427',Ref(stage) FROM ob_stage stage WHERE numStage=27;
INSERT INTO ob_etudiant SELECT 418,'nom428','prenom428',Ref(stage) FROM ob_stage stage WHERE numStage=33;
INSERT INTO ob_etudiant SELECT 419,'nom429','prenom429',Ref(stage) FROM ob_stage stage WHERE numStage=22;
INSERT INTO ob_etudiant SELECT 420,'nom430','prenom430',Ref(stage) FROM ob_stage stage WHERE numStage=19;
INSERT INTO ob_etudiant SELECT 421,'nom431','prenom431',Ref(stage) FROM ob_stage stage WHERE numStage=9;
INSERT INTO ob_etudiant SELECT 422,'nom432','prenom432',Ref(stage) FROM ob_stage stage WHERE numStage=47;
INSERT INTO ob_etudiant SELECT 423,'nom433','prenom433',Ref(stage) FROM ob_stage stage WHERE numStage=28;
INSERT INTO ob_etudiant SELECT 424,'nom434','prenom434',Ref(stage) FROM ob_stage stage WHERE numStage=40;
INSERT INTO ob_etudiant SELECT 425,'nom435','prenom435',Ref(stage) FROM ob_stage stage WHERE numStage=27;
INSERT INTO ob_etudiant SELECT 426,'nom436','prenom436',Ref(stage) FROM ob_stage stage WHERE numStage=26;
INSERT INTO ob_etudiant SELECT 427,'nom437','prenom437',Ref(stage) FROM ob_stage stage WHERE numStage=7;
INSERT INTO ob_etudiant SELECT 428,'nom438','prenom438',Ref(stage) FROM ob_stage stage WHERE numStage=17;
INSERT INTO ob_etudiant SELECT 429,'nom439','prenom439',Ref(stage) FROM ob_stage stage WHERE numStage=16;
INSERT INTO ob_etudiant SELECT 430,'nom440','prenom440',Ref(stage) FROM ob_stage stage WHERE numStage=25;
INSERT INTO ob_etudiant SELECT 431,'nom441','prenom441',Ref(stage) FROM ob_stage stage WHERE numStage=46;
INSERT INTO ob_etudiant SELECT 432,'nom442','prenom442',Ref(stage) FROM ob_stage stage WHERE numStage=10;
INSERT INTO ob_etudiant SELECT 433,'nom443','prenom443',Ref(stage) FROM ob_stage stage WHERE numStage=3;
INSERT INTO ob_etudiant SELECT 434,'nom444','prenom444',Ref(stage) FROM ob_stage stage WHERE numStage=45;
INSERT INTO ob_etudiant SELECT 435,'nom445','prenom445',Ref(stage) FROM ob_stage stage WHERE numStage=33;
INSERT INTO ob_etudiant SELECT 436,'nom446','prenom446',Ref(stage) FROM ob_stage stage WHERE numStage=28;
INSERT INTO ob_etudiant SELECT 437,'nom447','prenom447',Ref(stage) FROM ob_stage stage WHERE numStage=28;
INSERT INTO ob_etudiant SELECT 438,'nom448','prenom448',Ref(stage) FROM ob_stage stage WHERE numStage=12;
INSERT INTO ob_etudiant SELECT 439,'nom449','prenom449',Ref(stage) FROM ob_stage stage WHERE numStage=32;
INSERT INTO ob_etudiant SELECT 440,'nom450','prenom450',Ref(stage) FROM ob_stage stage WHERE numStage=19;
INSERT INTO ob_etudiant SELECT 441,'nom451','prenom451',Ref(stage) FROM ob_stage stage WHERE numStage=17;
INSERT INTO ob_etudiant SELECT 442,'nom452','prenom452',Ref(stage) FROM ob_stage stage WHERE numStage=14;
INSERT INTO ob_etudiant SELECT 443,'nom453','prenom453',Ref(stage) FROM ob_stage stage WHERE numStage=44;
INSERT INTO ob_etudiant SELECT 444,'nom454','prenom454',Ref(stage) FROM ob_stage stage WHERE numStage=32;
INSERT INTO ob_etudiant SELECT 445,'nom455','prenom455',Ref(stage) FROM ob_stage stage WHERE numStage=44;
INSERT INTO ob_etudiant SELECT 446,'nom456','prenom456',Ref(stage) FROM ob_stage stage WHERE numStage=24;
INSERT INTO ob_etudiant SELECT 447,'nom457','prenom457',Ref(stage) FROM ob_stage stage WHERE numStage=44;
INSERT INTO ob_etudiant SELECT 448,'nom458','prenom458',Ref(stage) FROM ob_stage stage WHERE numStage=2;
INSERT INTO ob_etudiant SELECT 449,'nom459','prenom459',Ref(stage) FROM ob_stage stage WHERE numStage=15;
INSERT INTO ob_etudiant SELECT 450,'nom460','prenom460',Ref(stage) FROM ob_stage stage WHERE numStage=48;
INSERT INTO ob_etudiant SELECT 451,'nom461','prenom461',Ref(stage) FROM ob_stage stage WHERE numStage=46;
INSERT INTO ob_etudiant SELECT 452,'nom462','prenom462',Ref(stage) FROM ob_stage stage WHERE numStage=38;
INSERT INTO ob_etudiant SELECT 453,'nom463','prenom463',Ref(stage) FROM ob_stage stage WHERE numStage=41;
INSERT INTO ob_etudiant SELECT 454,'nom464','prenom464',Ref(stage) FROM ob_stage stage WHERE numStage=33;
INSERT INTO ob_etudiant SELECT 455,'nom465','prenom465',Ref(stage) FROM ob_stage stage WHERE numStage=32;
INSERT INTO ob_etudiant SELECT 456,'nom466','prenom466',Ref(stage) FROM ob_stage stage WHERE numStage=38;
INSERT INTO ob_etudiant SELECT 457,'nom467','prenom467',Ref(stage) FROM ob_stage stage WHERE numStage=28;
INSERT INTO ob_etudiant SELECT 458,'nom468','prenom468',Ref(stage) FROM ob_stage stage WHERE numStage=33;
INSERT INTO ob_etudiant SELECT 459,'nom469','prenom469',Ref(stage) FROM ob_stage stage WHERE numStage=10;
INSERT INTO ob_etudiant SELECT 460,'nom470','prenom470',Ref(stage) FROM ob_stage stage WHERE numStage=13;
INSERT INTO ob_etudiant SELECT 461,'nom471','prenom471',Ref(stage) FROM ob_stage stage WHERE numStage=47;
INSERT INTO ob_etudiant SELECT 462,'nom472','prenom472',Ref(stage) FROM ob_stage stage WHERE numStage=6;
INSERT INTO ob_etudiant SELECT 463,'nom473','prenom473',Ref(stage) FROM ob_stage stage WHERE numStage=13;
INSERT INTO ob_etudiant SELECT 464,'nom474','prenom474',Ref(stage) FROM ob_stage stage WHERE numStage=12;
INSERT INTO ob_etudiant SELECT 465,'nom475','prenom475',Ref(stage) FROM ob_stage stage WHERE numStage=11;
INSERT INTO ob_etudiant SELECT 466,'nom476','prenom476',Ref(stage) FROM ob_stage stage WHERE numStage=14;
INSERT INTO ob_etudiant SELECT 467,'nom477','prenom477',Ref(stage) FROM ob_stage stage WHERE numStage=7;
INSERT INTO ob_etudiant SELECT 468,'nom478','prenom478',Ref(stage) FROM ob_stage stage WHERE numStage=9;
INSERT INTO ob_etudiant SELECT 469,'nom479','prenom479',Ref(stage) FROM ob_stage stage WHERE numStage=40;
INSERT INTO ob_etudiant SELECT 470,'nom480','prenom480',Ref(stage) FROM ob_stage stage WHERE numStage=30;
INSERT INTO ob_etudiant SELECT 471,'nom481','prenom481',Ref(stage) FROM ob_stage stage WHERE numStage=16;
INSERT INTO ob_etudiant SELECT 472,'nom482','prenom482',Ref(stage) FROM ob_stage stage WHERE numStage=17;
INSERT INTO ob_etudiant SELECT 473,'nom483','prenom483',Ref(stage) FROM ob_stage stage WHERE numStage=23;
INSERT INTO ob_etudiant SELECT 474,'nom484','prenom484',Ref(stage) FROM ob_stage stage WHERE numStage=14;
INSERT INTO ob_etudiant SELECT 475,'nom485','prenom485',Ref(stage) FROM ob_stage stage WHERE numStage=9;
INSERT INTO ob_etudiant SELECT 476,'nom486','prenom486',Ref(stage) FROM ob_stage stage WHERE numStage=15;
INSERT INTO ob_etudiant SELECT 477,'nom487','prenom487',Ref(stage) FROM ob_stage stage WHERE numStage=5;
INSERT INTO ob_etudiant SELECT 478,'nom488','prenom488',Ref(stage) FROM ob_stage stage WHERE numStage=36;
INSERT INTO ob_etudiant SELECT 479,'nom489','prenom489',Ref(stage) FROM ob_stage stage WHERE numStage=30;
INSERT INTO ob_etudiant SELECT 480,'nom490','prenom490',Ref(stage) FROM ob_stage stage WHERE numStage=43;
INSERT INTO ob_etudiant SELECT 481,'nom491','prenom491',Ref(stage) FROM ob_stage stage WHERE numStage=13;
INSERT INTO ob_etudiant SELECT 482,'nom492','prenom492',Ref(stage) FROM ob_stage stage WHERE numStage=38;
INSERT INTO ob_etudiant SELECT 483,'nom493','prenom493',Ref(stage) FROM ob_stage stage WHERE numStage=46;
INSERT INTO ob_etudiant SELECT 484,'nom494','prenom494',Ref(stage) FROM ob_stage stage WHERE numStage=26;
INSERT INTO ob_etudiant SELECT 485,'nom495','prenom495',Ref(stage) FROM ob_stage stage WHERE numStage=47;
INSERT INTO ob_etudiant SELECT 486,'nom496','prenom496',Ref(stage) FROM ob_stage stage WHERE numStage=19;
INSERT INTO ob_etudiant SELECT 487,'nom497','prenom497',Ref(stage) FROM ob_stage stage WHERE numStage=35;
INSERT INTO ob_etudiant SELECT 488,'nom498','prenom498',Ref(stage) FROM ob_stage stage WHERE numStage=45;
INSERT INTO ob_etudiant SELECT 489,'nom499','prenom499',Ref(stage) FROM ob_stage stage WHERE numStage=42;
INSERT INTO ob_etudiant SELECT 490,'nom500','prenom500',Ref(stage) FROM ob_stage stage WHERE numStage=32;
INSERT INTO ob_etudiant SELECT 491,'nom501','prenom501',Ref(stage) FROM ob_stage stage WHERE numStage=35;
INSERT INTO ob_etudiant SELECT 492,'nom502','prenom502',Ref(stage) FROM ob_stage stage WHERE numStage=16;
INSERT INTO ob_etudiant SELECT 493,'nom503','prenom503',Ref(stage) FROM ob_stage stage WHERE numStage=36;
INSERT INTO ob_etudiant SELECT 494,'nom504','prenom504',Ref(stage) FROM ob_stage stage WHERE numStage=39;
INSERT INTO ob_etudiant SELECT 495,'nom505','prenom505',Ref(stage) FROM ob_stage stage WHERE numStage=10;
INSERT INTO ob_etudiant SELECT 496,'nom506','prenom506',Ref(stage) FROM ob_stage stage WHERE numStage=32;
INSERT INTO ob_etudiant SELECT 497,'nom507','prenom507',Ref(stage) FROM ob_stage stage WHERE numStage=28;
INSERT INTO ob_etudiant SELECT 498,'nom508','prenom508',Ref(stage) FROM ob_stage stage WHERE numStage=32;
INSERT INTO ob_etudiant SELECT 499,'nom509','prenom509',Ref(stage) FROM ob_stage stage WHERE numStage=25;
INSERT INTO ob_etudiant SELECT 500,'nom510','prenom510',Ref(stage) FROM ob_stage stage WHERE numStage=4;
INSERT INTO ob_etudiant SELECT 501,'nom511','prenom511',Ref(stage) FROM ob_stage stage WHERE numStage=2;
INSERT INTO ob_etudiant SELECT 502,'nom512','prenom512',Ref(stage) FROM ob_stage stage WHERE numStage=29;
INSERT INTO ob_etudiant SELECT 503,'nom513','prenom513',Ref(stage) FROM ob_stage stage WHERE numStage=10;
INSERT INTO ob_etudiant SELECT 504,'nom514','prenom514',Ref(stage) FROM ob_stage stage WHERE numStage=17;
INSERT INTO ob_etudiant SELECT 505,'nom515','prenom515',Ref(stage) FROM ob_stage stage WHERE numStage=21;
INSERT INTO ob_etudiant SELECT 506,'nom516','prenom516',Ref(stage) FROM ob_stage stage WHERE numStage=10;
INSERT INTO ob_etudiant SELECT 507,'nom517','prenom517',Ref(stage) FROM ob_stage stage WHERE numStage=31;
INSERT INTO ob_etudiant SELECT 508,'nom518','prenom518',Ref(stage) FROM ob_stage stage WHERE numStage=16;
INSERT INTO ob_etudiant SELECT 509,'nom519','prenom519',Ref(stage) FROM ob_stage stage WHERE numStage=39;
INSERT INTO ob_etudiant SELECT 510,'nom520','prenom520',Ref(stage) FROM ob_stage stage WHERE numStage=47;
INSERT INTO ob_etudiant SELECT 511,'nom521','prenom521',Ref(stage) FROM ob_stage stage WHERE numStage=33;
INSERT INTO ob_etudiant SELECT 512,'nom522','prenom522',Ref(stage) FROM ob_stage stage WHERE numStage=8;
INSERT INTO ob_etudiant SELECT 513,'nom523','prenom523',Ref(stage) FROM ob_stage stage WHERE numStage=15;
INSERT INTO ob_etudiant SELECT 514,'nom524','prenom524',Ref(stage) FROM ob_stage stage WHERE numStage=26;
INSERT INTO ob_etudiant SELECT 515,'nom525','prenom525',Ref(stage) FROM ob_stage stage WHERE numStage=19;
INSERT INTO ob_etudiant SELECT 516,'nom526','prenom526',Ref(stage) FROM ob_stage stage WHERE numStage=6;
INSERT INTO ob_etudiant SELECT 517,'nom527','prenom527',Ref(stage) FROM ob_stage stage WHERE numStage=21;
INSERT INTO ob_etudiant SELECT 518,'nom528','prenom528',Ref(stage) FROM ob_stage stage WHERE numStage=19;
INSERT INTO ob_etudiant SELECT 519,'nom529','prenom529',Ref(stage) FROM ob_stage stage WHERE numStage=3;
INSERT INTO ob_etudiant SELECT 520,'nom530','prenom530',Ref(stage) FROM ob_stage stage WHERE numStage=26;
INSERT INTO ob_etudiant SELECT 521,'nom531','prenom531',Ref(stage) FROM ob_stage stage WHERE numStage=3;
INSERT INTO ob_etudiant SELECT 522,'nom532','prenom532',Ref(stage) FROM ob_stage stage WHERE numStage=48;
INSERT INTO ob_etudiant SELECT 523,'nom533','prenom533',Ref(stage) FROM ob_stage stage WHERE numStage=45;
INSERT INTO ob_etudiant SELECT 524,'nom534','prenom534',Ref(stage) FROM ob_stage stage WHERE numStage=2;
INSERT INTO ob_etudiant SELECT 525,'nom535','prenom535',Ref(stage) FROM ob_stage stage WHERE numStage=23;
INSERT INTO ob_etudiant SELECT 526,'nom536','prenom536',Ref(stage) FROM ob_stage stage WHERE numStage=26;
INSERT INTO ob_etudiant SELECT 527,'nom537','prenom537',Ref(stage) FROM ob_stage stage WHERE numStage=32;
INSERT INTO ob_etudiant SELECT 528,'nom538','prenom538',Ref(stage) FROM ob_stage stage WHERE numStage=14;
INSERT INTO ob_etudiant SELECT 529,'nom539','prenom539',Ref(stage) FROM ob_stage stage WHERE numStage=16;
INSERT INTO ob_etudiant SELECT 530,'nom540','prenom540',Ref(stage) FROM ob_stage stage WHERE numStage=4;
INSERT INTO ob_etudiant SELECT 531,'nom541','prenom541',Ref(stage) FROM ob_stage stage WHERE numStage=2;
INSERT INTO ob_etudiant SELECT 532,'nom542','prenom542',Ref(stage) FROM ob_stage stage WHERE numStage=40;
INSERT INTO ob_etudiant SELECT 533,'nom543','prenom543',Ref(stage) FROM ob_stage stage WHERE numStage=28;
INSERT INTO ob_etudiant SELECT 534,'nom544','prenom544',Ref(stage) FROM ob_stage stage WHERE numStage=48;
INSERT INTO ob_etudiant SELECT 535,'nom545','prenom545',Ref(stage) FROM ob_stage stage WHERE numStage=15;
INSERT INTO ob_etudiant SELECT 536,'nom546','prenom546',Ref(stage) FROM ob_stage stage WHERE numStage=10;
INSERT INTO ob_etudiant SELECT 537,'nom547','prenom547',Ref(stage) FROM ob_stage stage WHERE numStage=9;
INSERT INTO ob_etudiant SELECT 538,'nom548','prenom548',Ref(stage) FROM ob_stage stage WHERE numStage=6;
INSERT INTO ob_etudiant SELECT 539,'nom549','prenom549',Ref(stage) FROM ob_stage stage WHERE numStage=7;
INSERT INTO ob_etudiant SELECT 540,'nom550','prenom550',Ref(stage) FROM ob_stage stage WHERE numStage=22;
INSERT INTO ob_etudiant SELECT 541,'nom551','prenom551',Ref(stage) FROM ob_stage stage WHERE numStage=44;
INSERT INTO ob_etudiant SELECT 542,'nom552','prenom552',Ref(stage) FROM ob_stage stage WHERE numStage=13;
INSERT INTO ob_etudiant SELECT 543,'nom553','prenom553',Ref(stage) FROM ob_stage stage WHERE numStage=48;
INSERT INTO ob_etudiant SELECT 544,'nom554','prenom554',Ref(stage) FROM ob_stage stage WHERE numStage=8;
INSERT INTO ob_etudiant SELECT 545,'nom555','prenom555',Ref(stage) FROM ob_stage stage WHERE numStage=3;
INSERT INTO ob_etudiant SELECT 546,'nom556','prenom556',Ref(stage) FROM ob_stage stage WHERE numStage=7;
INSERT INTO ob_etudiant SELECT 547,'nom557','prenom557',Ref(stage) FROM ob_stage stage WHERE numStage=26;
INSERT INTO ob_etudiant SELECT 548,'nom558','prenom558',Ref(stage) FROM ob_stage stage WHERE numStage=44;
INSERT INTO ob_etudiant SELECT 549,'nom559','prenom559',Ref(stage) FROM ob_stage stage WHERE numStage=16;
INSERT INTO ob_etudiant SELECT 550,'nom560','prenom560',Ref(stage) FROM ob_stage stage WHERE numStage=46;
INSERT INTO ob_etudiant SELECT 551,'nom561','prenom561',Ref(stage) FROM ob_stage stage WHERE numStage=20;
INSERT INTO ob_etudiant SELECT 552,'nom562','prenom562',Ref(stage) FROM ob_stage stage WHERE numStage=18;
INSERT INTO ob_etudiant SELECT 553,'nom563','prenom563',Ref(stage) FROM ob_stage stage WHERE numStage=10;
INSERT INTO ob_etudiant SELECT 554,'nom564','prenom564',Ref(stage) FROM ob_stage stage WHERE numStage=43;
INSERT INTO ob_etudiant SELECT 555,'nom565','prenom565',Ref(stage) FROM ob_stage stage WHERE numStage=41;
INSERT INTO ob_etudiant SELECT 556,'nom566','prenom566',Ref(stage) FROM ob_stage stage WHERE numStage=28;
INSERT INTO ob_etudiant SELECT 557,'nom567','prenom567',Ref(stage) FROM ob_stage stage WHERE numStage=22;
INSERT INTO ob_etudiant SELECT 558,'nom568','prenom568',Ref(stage) FROM ob_stage stage WHERE numStage=11;
INSERT INTO ob_etudiant SELECT 559,'nom569','prenom569',Ref(stage) FROM ob_stage stage WHERE numStage=42;
INSERT INTO ob_etudiant SELECT 560,'nom570','prenom570',Ref(stage) FROM ob_stage stage WHERE numStage=13;
INSERT INTO ob_etudiant SELECT 561,'nom571','prenom571',Ref(stage) FROM ob_stage stage WHERE numStage=42;
INSERT INTO ob_etudiant SELECT 562,'nom572','prenom572',Ref(stage) FROM ob_stage stage WHERE numStage=10;
INSERT INTO ob_etudiant SELECT 563,'nom573','prenom573',Ref(stage) FROM ob_stage stage WHERE numStage=25;
INSERT INTO ob_etudiant SELECT 564,'nom574','prenom574',Ref(stage) FROM ob_stage stage WHERE numStage=20;
INSERT INTO ob_etudiant SELECT 565,'nom575','prenom575',Ref(stage) FROM ob_stage stage WHERE numStage=45;
INSERT INTO ob_etudiant SELECT 566,'nom576','prenom576',Ref(stage) FROM ob_stage stage WHERE numStage=39;
INSERT INTO ob_etudiant SELECT 567,'nom577','prenom577',Ref(stage) FROM ob_stage stage WHERE numStage=44;
INSERT INTO ob_etudiant SELECT 568,'nom578','prenom578',Ref(stage) FROM ob_stage stage WHERE numStage=7;
INSERT INTO ob_etudiant SELECT 569,'nom579','prenom579',Ref(stage) FROM ob_stage stage WHERE numStage=43;
INSERT INTO ob_etudiant SELECT 570,'nom580','prenom580',Ref(stage) FROM ob_stage stage WHERE numStage=23;
INSERT INTO ob_etudiant SELECT 571,'nom581','prenom581',Ref(stage) FROM ob_stage stage WHERE numStage=11;
INSERT INTO ob_etudiant SELECT 572,'nom582','prenom582',Ref(stage) FROM ob_stage stage WHERE numStage=29;
INSERT INTO ob_etudiant SELECT 573,'nom583','prenom583',Ref(stage) FROM ob_stage stage WHERE numStage=36;
INSERT INTO ob_etudiant SELECT 574,'nom584','prenom584',Ref(stage) FROM ob_stage stage WHERE numStage=17;
INSERT INTO ob_etudiant SELECT 575,'nom585','prenom585',Ref(stage) FROM ob_stage stage WHERE numStage=19;
INSERT INTO ob_etudiant SELECT 576,'nom586','prenom586',Ref(stage) FROM ob_stage stage WHERE numStage=13;
INSERT INTO ob_etudiant SELECT 577,'nom587','prenom587',Ref(stage) FROM ob_stage stage WHERE numStage=20;
INSERT INTO ob_etudiant SELECT 578,'nom588','prenom588',Ref(stage) FROM ob_stage stage WHERE numStage=20;
INSERT INTO ob_etudiant SELECT 579,'nom589','prenom589',Ref(stage) FROM ob_stage stage WHERE numStage=41;
INSERT INTO ob_etudiant SELECT 580,'nom590','prenom590',Ref(stage) FROM ob_stage stage WHERE numStage=18;
INSERT INTO ob_etudiant SELECT 581,'nom591','prenom591',Ref(stage) FROM ob_stage stage WHERE numStage=19;
INSERT INTO ob_etudiant SELECT 582,'nom592','prenom592',Ref(stage) FROM ob_stage stage WHERE numStage=30;
INSERT INTO ob_etudiant SELECT 583,'nom593','prenom593',Ref(stage) FROM ob_stage stage WHERE numStage=6;
INSERT INTO ob_etudiant SELECT 584,'nom594','prenom594',Ref(stage) FROM ob_stage stage WHERE numStage=28;
INSERT INTO ob_etudiant SELECT 585,'nom595','prenom595',Ref(stage) FROM ob_stage stage WHERE numStage=42;
INSERT INTO ob_etudiant SELECT 586,'nom596','prenom596',Ref(stage) FROM ob_stage stage WHERE numStage=31;
INSERT INTO ob_etudiant SELECT 587,'nom597','prenom597',Ref(stage) FROM ob_stage stage WHERE numStage=31;
INSERT INTO ob_etudiant SELECT 588,'nom598','prenom598',Ref(stage) FROM ob_stage stage WHERE numStage=2;
INSERT INTO ob_etudiant SELECT 589,'nom599','prenom599',Ref(stage) FROM ob_stage stage WHERE numStage=9;
INSERT INTO ob_etudiant SELECT 590,'nom600','prenom600',Ref(stage) FROM ob_stage stage WHERE numStage=2;
INSERT INTO ob_etudiant SELECT 591,'nom601','prenom601',Ref(stage) FROM ob_stage stage WHERE numStage=9;
INSERT INTO ob_etudiant SELECT 592,'nom602','prenom602',Ref(stage) FROM ob_stage stage WHERE numStage=39;
INSERT INTO ob_etudiant SELECT 593,'nom603','prenom603',Ref(stage) FROM ob_stage stage WHERE numStage=26;
INSERT INTO ob_etudiant SELECT 594,'nom604','prenom604',Ref(stage) FROM ob_stage stage WHERE numStage=42;
INSERT INTO ob_etudiant SELECT 595,'nom605','prenom605',Ref(stage) FROM ob_stage stage WHERE numStage=8;
INSERT INTO ob_etudiant SELECT 596,'nom606','prenom606',Ref(stage) FROM ob_stage stage WHERE numStage=31;
INSERT INTO ob_etudiant SELECT 597,'nom607','prenom607',Ref(stage) FROM ob_stage stage WHERE numStage=9;
INSERT INTO ob_etudiant SELECT 598,'nom608','prenom608',Ref(stage) FROM ob_stage stage WHERE numStage=31;
INSERT INTO ob_etudiant SELECT 599,'nom609','prenom609',Ref(stage) FROM ob_stage stage WHERE numStage=35;
INSERT INTO ob_etudiant SELECT 600,'nom610','prenom610',Ref(stage) FROM ob_stage stage WHERE numStage=35;

commit;